### ISSUE TITLE
No commands defined in the "server" namespace. 

### ISSUE THREAD

**Issue by kemoc** [krzysiekpiasecki/Gentelella#60] opened 2017-10-05 13:05 UTC
After install can't start built in server:
`php bin/console server:run 127.0.0.1:8080 --env=prod`

> [Symfony\Component\Console\Exception\CommandNotFoundException]  
>  There are no commands defined in the "server" namespace. 

to reproduce just make clean install project on branch master.
Pozdrawiam

**Comment by kemoc** [comment] 2017-10-05 13:35
Found solution
Read section "FrameworkBundle". Server has own bundle now.
https://github.com/symfony/symfony/blob/master/UPGRADE-3.3.md
And one more thing, even fix this problem you instruction generate error in terminal:
`php bin/console server:run 127.0.0.1:8080 --env=prod`

>  [ERROR] The document root directory must be either passed as first argument of the constructor or through the          
>         "--docroot" input option.  

I suggest to replace in INSTALL.md to
`php bin/console server:run`

And please create stable version of this project with INSTALL.md, *.md, when i checkouted 2.1.2 
i haven't those files inside.

BR

**Comment by krzysiekpiasecki** [comment] 2017-10-05 21:00
Can't reproduce. Clean install was successful.

Have you run it?

```shell
$ cd /tmp
$ composer create-project krzysiekpiasecki/gentelella gentelella "dev-master"
$ cd gentelella
$ composer setup
$ composer test
$ php bin/console fos:user:create --super-admin
$ php bin/console server:run 127.0.0.1:8080 --env=prod
```

The problem is that you have updated dependencies. Frozen dependencies are in a lock file.
```The Symfony resolves to: symfony/symfony                      v3.2.7```

This project needs to be updated to fully support ```v3.3```

**Comment by kemoc** [comment] 2017-10-05 21:07
Yes, works,  but i have not check logs files so i do not know if there are problems..

**Comment by krzysiekpiasecki** [comment] 2017-10-05 21:11
Has it resolved this issue? If yes, please feel free to close this ticket and thank you very much Radek for your attention.

**Closed** 2017-10-05 21:12 UTC
